import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Effect } from "effect";
import { afterAll, beforeAll, describe, expect, it } from "@effect/vitest";
import { AUTHORING_META_KEY, AUTHORING_PACKAGE_VERSION } from "../src/authoring/package.js";
import {
  CLAUDE_SKILL_LOCATION,
  SHARED_SKILL_LOCATION,
  SKILL_NAME,
  skillMd,
} from "../src/authoring/skill.js";
import { skillStalenessHints } from "../src/commands/check/skill.js";
import { runSkillsInstall } from "../src/commands/skills/install.js";
import { frontmatterBlock } from "../src/walkthrough/frontmatter.js";
import { CORE_TAG_NAMES } from "../src/walkthrough/tags.js";
import { provideLive } from "./support/effect.js";
import { createFixtureRepo, type FixtureRepo } from "./support/repo.js";

const install = (options: { cwd: string; out?: string }) =>
  Effect.runPromise(provideLive(runSkillsInstall(options)));

const hints = (cwd: string) => Effect.runPromise(provideLive(skillStalenessHints(cwd)));

/** The installed skill with its frontmatter stamp rewritten to another version. */
function restamp(repoDir: string, location: string, version: string): void {
  const file = join(repoDir, location, SKILL_NAME, "SKILL.md");
  const source = readFileSync(file, "utf8");
  const block = frontmatterBlock(source);
  if (block === null) throw new Error(`no frontmatter in ${file}`);
  writeFileSync(
    file,
    source.replace(
      block,
      block.replace(
        `${AUTHORING_META_KEY}: ${AUTHORING_PACKAGE_VERSION}`,
        `${AUTHORING_META_KEY}: ${version}`,
      ),
    ),
    "utf8",
  );
}

describe("the generated authoring skill", () => {
  it("renders a stamped, self-describing SKILL.md", () => {
    const skill = skillMd;
    const block = frontmatterBlock(skill);
    expect(block).not.toBeNull();
    expect(block).toContain(`name: ${SKILL_NAME}`);
    expect(block).toContain("description: ");
    expect(block).toContain(`${AUTHORING_META_KEY}: ${AUTHORING_PACKAGE_VERSION}`);
    expect(skill).toContain("Do not edit this file");
    expect(skill).toContain("balade check");
    expect(skill).toContain(`walkthrough: 1`);
  });

  it("teaches every core tag's syntax, like the Pi prompt does", () => {
    const skill = skillMd;
    for (const tag of CORE_TAG_NAMES) {
      /* Pipe tables render as-is; the catalog shows no `{% table %}` wrapper. */
      if (tag === "table") continue;
      expect(skill).toContain(`{% ${tag}`);
    }
    expect(skill).toContain("Only code tags count against the range budget");
    expect(skill).toContain("ASD-STE100 Simplified Technical English");
  });
});

describe("skills install and the check staleness hint", () => {
  let repo: FixtureRepo;
  const scratchDirs: string[] = [];

  /** A throwaway directory that is not a git repository. */
  function outsideRepo(): string {
    const dir = mkdtempSync(join(tmpdir(), "balade-no-repo-"));
    scratchDirs.push(dir);
    return dir;
  }

  beforeAll(() => {
    repo = createFixtureRepo();
  });

  afterAll(() => {
    repo.cleanup();
    for (const dir of scratchDirs) rmSync(dir, { recursive: true, force: true });
  });

  it("writes the shared convention, and .claude/ only once the repo uses Claude Code", async () => {
    /* git and node spell the same directory differently (symlinked /var on
       macOS, short-vs-long form on Windows); compare canonical paths. */
    const canon = (file: string) => realpathSync.native(file);
    const shared = () => canon(join(repo.dir, SHARED_SKILL_LOCATION, SKILL_NAME, "SKILL.md"));
    const claude = () => canon(join(repo.dir, CLAUDE_SKILL_LOCATION, SKILL_NAME, "SKILL.md"));

    /* No `.claude/` folder yet: a non-Claude repository never grows one. */
    const first = await install({ cwd: repo.dir });
    expect(first.map(canon)).toEqual([shared()]);

    mkdirSync(join(repo.dir, ".claude"), { recursive: true });
    const written = await install({ cwd: repo.dir });
    expect(written.map(canon)).toEqual([claude(), shared()]);
    for (const file of written) expect(readFileSync(file, "utf8")).toBe(skillMd);
    /* A refresh overwrites in place. */
    expect((await install({ cwd: repo.dir })).map(canon)).toEqual(written.map(canon));
  });

  it("writes one custom directory with --out", async () => {
    const written = await install({ cwd: repo.dir, out: "dist/skill" });
    expect(written).toEqual([join(repo.dir, "dist/skill", SKILL_NAME, "SKILL.md")]);
    expect(readFileSync(written[0] ?? "", "utf8")).toBe(skillMd);
  });

  it("fails outside a git repository when no --out names a target", async () => {
    const error = await Effect.runPromise(
      provideLive(Effect.flip(runSkillsInstall({ cwd: outsideRepo() }))),
    );
    expect(error._tag).toBe("NotARepository");
  });

  it("stays silent while the installed skill is current", async () => {
    await install({ cwd: repo.dir });
    expect(await hints(repo.dir)).toEqual([]);
  });

  it("hints a re-install for a stale skill and an upgrade for a newer one", async () => {
    await install({ cwd: repo.dir });
    restamp(repo.dir, CLAUDE_SKILL_LOCATION, "1.0.0");
    const stale = await hints(repo.dir);
    expect(stale).toHaveLength(1);
    expect(stale[0]).toContain(`${CLAUDE_SKILL_LOCATION}/${SKILL_NAME}/SKILL.md`);
    expect(stale[0]).toContain("1.0.0");
    expect(stale[0]).toContain("balade skills install");

    restamp(repo.dir, SHARED_SKILL_LOCATION, "9.9.9");
    const mixed = await hints(repo.dir);
    expect(mixed).toHaveLength(2);
    expect(mixed.find((line) => line.includes("9.9.9"))).toContain("Upgrade balade");

    /* A re-install converges both directories back to silence. */
    await install({ cwd: repo.dir });
    expect(await hints(repo.dir)).toEqual([]);
  });

  it("ignores skill files without the stamp and stays silent outside a repository", async () => {
    const foreign = join(repo.dir, CLAUDE_SKILL_LOCATION, "some-other-skill");
    await install({ cwd: repo.dir });
    expect(await hints(outsideRepo())).toEqual([]);
    mkdirSync(foreign, { recursive: true });
    writeFileSync(join(foreign, "SKILL.md"), "---\nname: other\ndescription: d\n---\nBody.\n");
    expect(await hints(repo.dir)).toEqual([]);
  });
});
