/* The octicon names a payload may carry. The authoring package teaches this
   same list, and a test compares the two, so what an author may write and what
   the renderer maps cannot drift. */

export const ICON_NAMES = [
  "alert",
  "arrow-right",
  "beaker",
  "book",
  "check",
  "check-circle-fill",
  "chevron-down",
  "chevron-right",
  "circle",
  "code-square",
  "columns",
  "dash",
  "database",
  "diff-added",
  "diff-modified",
  "diff-removed",
  "diff-renamed",
  "dot-fill",
  "eye",
  "file",
  "file-added",
  "file-binary",
  "file-code",
  "file-diff",
  "gear",
  "git-branch",
  "git-commit",
  "git-compare",
  "git-merge",
  "git-pull-request",
  "globe",
  "graph",
  "info",
  "law",
  "light-bulb",
  "link",
  "link-external",
  "list-unordered",
  "package",
  "person",
  "question",
  "repo",
  "rows",
  "shield-lock",
  "sync",
  "table",
  "unfold",
  "x",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
